### ISSUE TITLE
Feature Request: Add Craft Event to beginning of verify() method in Recaptcha.php

### ISSUE THREAD

**Issue by creode-dev** [juban/craft-google-recaptcha#6]
Would it be possible to add a Craft CMS Event to the start of the verify() method in Recaptcha.php file. This would allow developers to listen to that event and return early out of the verify method. A use case for this would be to check agains an IP whitelist, and bypass Google Recaptcha. 

I would be happy to submit a pull request with the feature if required. But I just wanted to check if this feature is in line with the plugins development path.

**Comment by juban** [comment]
Hi @creode-dev,

Thank you for that idea.
However, as the `verify` method has to be called from your specific implementation (in a module), I'm just wondering why the additional checks should not be added there (ie. just don't call the verify method if any preventive checks fails)?

**Comment by creode-dev** [comment]
Hi @juban,

Thanks for coming back to us.

The reason for the request was to allow us to add similar functionality to a bunch of forms all from one event. This cuts back the requirement to repeat code for every form which supports reCAPTCHA (even if this is just a quick one line check to a service class). Doing this will mean that new functionality can be added/handled in single event handlers rather than having to repeat the same calls for every form on the website.

**Comment by juban** [comment]
Hi @creode-dev 
Sorry for the delay, I've been a bit busy lately.
Looks a legit use case to me.
Could you send a PR. I'll try to take a look quickly and merged it in a new release.

**Comment by creode-dev** [comment]
@juban Popped a PR in for this cheers. #7

**Comment by juban** [comment]
@creode-dev Thank you so much for your contribution.
As a side note, I've slightly refactored your PR in order to distinct skipped and canceled verifications (the event has been renamed `BeforeRecaptchaVerifyEvent` and is a CancelableEvent class child). I also added the according tests and documentation. Hope that will suits you. Thank you again for your help and feel free to come back to me for any issue regarding this.
Cheers.
