### ISSUE TITLE
Craft CMS v5 support

### ISSUE THREAD

**Issue by vaelu** [juban/craft-google-recaptcha#9]
Hi, is it planned that the plugin is updated to support Craft 5?

**Comment by juban** [comment]
Hi @vaelu ,

Yes, I will update the plugin to support Craft 5 eventually. However, as I'm very busy right now, I can't guarantee when I'll be able to achieve that. 
Stay tuned ;) Thanks.

**Comment by vaelu** [comment]
Hi @juban
Is there already an update on this?

**Comment by juban** [comment]
Hi @vaelu 
v3 with Craft 5 support and some improvements is finally here. 
Thank you for your patience and support.
